var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include <filesystem>"},
{"lineNum":"    4","line":"#include <mutex>"},
{"lineNum":"    5","line":"#include <utility>"},
{"lineNum":"    6","line":"#include <vector>"},
{"lineNum":"    7","line":""},
{"lineNum":"    8","line":"#include <gsl/pointers>"},
{"lineNum":"    9","line":"#include <stdx/assert.hh>"},
{"lineNum":"   10","line":"#include <stdx/fixed/hash_table.hh>"},
{"lineNum":"   11","line":"#include <stdx/fixed/vector.hh>"},
{"lineNum":"   12","line":"#include <stdx/memory.hh>"},
{"lineNum":"   13","line":"#include <stdx/option.hh>"},
{"lineNum":"   14","line":"#include <stdx/result.hh>"},
{"lineNum":"   15","line":"#include <stdx/types.hh>"},
{"lineNum":"   16","line":"#include <stdx/utility.hh>"},
{"lineNum":"   17","line":""},
{"lineNum":"   18","line":"#include \"storage/disk_manager.hh\""},
{"lineNum":"   19","line":"#include \"storage/frame_replacer.hh\""},
{"lineNum":"   20","line":"#include \"storage/page.hh\""},
{"lineNum":"   21","line":"#include \"support/diagnostic/error.hh\""},
{"lineNum":"   22","line":"#include \"wal/checkpoint/types.hh\""},
{"lineNum":"   23","line":"#include \"wal/log/manager.hh\""},
{"lineNum":"   24","line":""},
{"lineNum":"   25","line":"namespace cairn::storage {"},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"template <usize PoolSize> class buffer_pool;"},
{"lineNum":"   28","line":""},
{"lineNum":"   29","line":"// RAII holding a shared latch on a pinned page"},
{"lineNum":"   30","line":"template <usize PoolSize>"},
{"lineNum":"   31","line":"    requires(PoolSize > 0)"},
{"lineNum":"   32","line":"class read_guard {"},
{"lineNum":"   33","line":"  public:"},
{"lineNum":"   34","line":"    constexpr read_guard() noexcept = default;"},
{"lineNum":"   35","line":"    read_guard(buffer_pool<PoolSize>& pool, page& pg) noexcept : pool_{pool}, pg_{pg} {}","class":"lineCov","hits":"1","order":"1135",},
{"lineNum":"   36","line":"    ~read_guard() { drop(); }","class":"lineCov","hits":"1","order":"1133",},
{"lineNum":"   37","line":""},
{"lineNum":"   38","line":"    read_guard(const read_guard&)                    = delete;"},
{"lineNum":"   39","line":"    auto operator=(const read_guard&) -> read_guard& = delete;"},
{"lineNum":"   40","line":""},
{"lineNum":"   41","line":"    read_guard(read_guard&& other) noexcept : pool_{other.pool_}, pg_{other.pg_} {","class":"lineCov","hits":"1","order":"1124",},
{"lineNum":"   42","line":"        other.pool_.reset();","class":"lineCov","hits":"1","order":"1122",},
{"lineNum":"   43","line":"        other.pg_.reset();","class":"lineCov","hits":"1","order":"1120",},
{"lineNum":"   44","line":"    }","class":"lineCov","hits":"1","order":"1018",},
{"lineNum":"   45","line":""},
{"lineNum":"   46","line":"    auto operator=(read_guard&& other) noexcept -> read_guard& {","class":"lineCov","hits":"1","order":"1117",},
{"lineNum":"   47","line":"        if (this != &other) {","class":"lineCov","hits":"1","order":"1115",},
{"lineNum":"   48","line":"            drop();","class":"lineCov","hits":"1","order":"1113",},
{"lineNum":"   49","line":"            pool_ = other.pool_;","class":"lineCov","hits":"1","order":"1110",},
{"lineNum":"   50","line":"            pg_   = other.pg_;","class":"lineCov","hits":"1","order":"1107",},
{"lineNum":"   51","line":"            other.pool_.reset();","class":"lineCov","hits":"1","order":"1103",},
{"lineNum":"   52","line":"            other.pg_.reset();","class":"lineCov","hits":"1","order":"1099",},
{"lineNum":"   53","line":"        }"},
{"lineNum":"   54","line":"        return *this;","class":"lineCov","hits":"1","order":"1093",},
{"lineNum":"   55","line":"    }"},
{"lineNum":"   56","line":""},
{"lineNum":"   57","line":"    [[nodiscard]] auto valid() const noexcept -> bool { return pool_.has_value(); }"},
{"lineNum":"   58","line":"    [[nodiscard]] auto page_id() const noexcept -> page_id_t { return pg_->page_id(); }"},
{"lineNum":"   59","line":""},
{"lineNum":"   60","line":"    // Read-only view of the page\'s bytes"},
{"lineNum":"   61","line":"    template <typename T> [[nodiscard]] auto as() const noexcept -> gsl::not_null<const T*> {","class":"lineCov","hits":"1","order":"1149",},
{"lineNum":"   62","line":"        return stdx::object_at<T>(pg_->data());","class":"lineCov","hits":"1","order":"1017",},
{"lineNum":"   63","line":"    }"},
{"lineNum":"   64","line":""},
{"lineNum":"   65","line":"    [[nodiscard]] auto get(this auto&& self) noexcept { return gsl::not_null{self.pg_.get()}; }","class":"lineCov","hits":"1","order":"991",},
{"lineNum":"   66","line":""},
{"lineNum":"   67","line":"    // Called automatically on destruction but safe to call manually"},
{"lineNum":"   68","line":"    auto drop() noexcept -> void {","class":"lineCov","hits":"1","order":"1002",},
{"lineNum":"   69","line":"        if (pool_) {","class":"lineCov","hits":"1","order":"1001",},
{"lineNum":"   70","line":"            const auto pid{pg_->page_id()};","class":"lineCov","hits":"1","order":"1000",},
{"lineNum":"   71","line":"            pg_->latch().unlock_shared();","class":"lineCov","hits":"1","order":"999",},
{"lineNum":"   72","line":"            DISCARD(pool_->unpin_page(pid, false));","class":"lineCov","hits":"1","order":"1056",},
{"lineNum":"   73","line":"            pool_.reset();","class":"lineCov","hits":"1","order":"1054",},
{"lineNum":"   74","line":"            pg_.reset();","class":"lineCov","hits":"1","order":"1052",},
{"lineNum":"   75","line":"        }"},
{"lineNum":"   76","line":"    }","class":"lineCov","hits":"1","order":"1050",},
{"lineNum":"   77","line":""},
{"lineNum":"   78","line":"  private:"},
{"lineNum":"   79","line":"    stdx::option<buffer_pool<PoolSize>&> pool_;"},
{"lineNum":"   80","line":"    stdx::option<page&>                  pg_;"},
{"lineNum":"   81","line":"};"},
{"lineNum":"   82","line":""},
{"lineNum":"   83","line":"// RAII holding an exclusive latch on a pinned page"},
{"lineNum":"   84","line":"template <usize PoolSize>"},
{"lineNum":"   85","line":"    requires(PoolSize > 0)"},
{"lineNum":"   86","line":"class write_guard {"},
{"lineNum":"   87","line":"  public:"},
{"lineNum":"   88","line":"    constexpr write_guard() noexcept = default;","class":"lineCov","hits":"1","order":"993",},
{"lineNum":"   89","line":"    write_guard(buffer_pool<PoolSize>& pool, page& pg) noexcept : pool_{pool}, pg_{pg} {}","class":"lineCov","hits":"1","order":"1016",},
{"lineNum":"   90","line":"    ~write_guard() { drop(); }","class":"lineCov","hits":"1","order":"1014",},
{"lineNum":"   91","line":""},
{"lineNum":"   92","line":"    write_guard(const write_guard&)                    = delete;"},
{"lineNum":"   93","line":"    auto operator=(const write_guard&) -> write_guard& = delete;"},
{"lineNum":"   94","line":""},
{"lineNum":"   95","line":"    write_guard(write_guard&& other) noexcept"},
{"lineNum":"   96","line":"        : pool_{other.pool_}, pg_{other.pg_}, dirty_{other.dirty_} {","class":"lineCov","hits":"1","order":"1013",},
{"lineNum":"   97","line":"        other.pool_.reset();","class":"lineCov","hits":"1","order":"1012",},
{"lineNum":"   98","line":"        other.pg_.reset();","class":"lineCov","hits":"1","order":"1011",},
{"lineNum":"   99","line":"    }","class":"lineCov","hits":"1","order":"1023",},
{"lineNum":"  100","line":""},
{"lineNum":"  101","line":"    auto operator=(write_guard&& other) noexcept -> write_guard& {"},
{"lineNum":"  102","line":"        if (this != &other) {"},
{"lineNum":"  103","line":"            drop();"},
{"lineNum":"  104","line":"            pool_  = other.pool_;"},
{"lineNum":"  105","line":"            pg_    = other.pg_;"},
{"lineNum":"  106","line":"            dirty_ = other.dirty_;"},
{"lineNum":"  107","line":"            other.pool_.reset();"},
{"lineNum":"  108","line":"            other.pg_.reset();"},
{"lineNum":"  109","line":"        }"},
{"lineNum":"  110","line":"        return *this;"},
{"lineNum":"  111","line":"    }"},
{"lineNum":"  112","line":""},
{"lineNum":"  113","line":"    [[nodiscard]] auto valid() const noexcept -> bool { return pool_.has_value(); }"},
{"lineNum":"  114","line":"    [[nodiscard]] auto page_id() const noexcept -> page_id_t { return pg_->page_id(); }","class":"lineCov","hits":"1","order":"1027",},
{"lineNum":"  115","line":"    auto               mark_dirty() noexcept -> void { dirty_ = true; }","class":"lineCov","hits":"1","order":"1025",},
{"lineNum":"  116","line":""},
{"lineNum":"  117","line":"    template <typename T> [[nodiscard]] auto as(this auto&& self) noexcept -> auto* {","class":"lineCov","hits":"1","order":"1144",},
{"lineNum":"  118","line":"        return stdx::object_at<T>(self.pg_->data());","class":"lineCov","hits":"1","order":"1142",},
{"lineNum":"  119","line":"    }"},
{"lineNum":"  120","line":""},
{"lineNum":"  121","line":"    [[nodiscard]] auto get(this auto&& self) noexcept { return gsl::not_null{self.pg_.get()}; }","class":"lineCov","hits":"1","order":"1128",},
{"lineNum":"  122","line":""},
{"lineNum":"  123","line":"    // Called automatically on destruction but safe to call manually"},
{"lineNum":"  124","line":"    auto drop() noexcept -> void {","class":"lineCov","hits":"1","order":"1010",},
{"lineNum":"  125","line":"        if (pool_) {","class":"lineCov","hits":"1","order":"1009",},
{"lineNum":"  126","line":"            const auto pid{pg_->page_id()};","class":"lineCov","hits":"1","order":"1008",},
{"lineNum":"  127","line":"            pg_->latch().unlock();","class":"lineCov","hits":"1","order":"1007",},
{"lineNum":"  128","line":"            DISCARD(pool_->unpin_page(pid, dirty_));","class":"lineCov","hits":"1","order":"1006",},
{"lineNum":"  129","line":"            pool_.reset();","class":"lineCov","hits":"1","order":"1005",},
{"lineNum":"  130","line":"            pg_.reset();","class":"lineCov","hits":"1","order":"1004",},
{"lineNum":"  131","line":"        }"},
{"lineNum":"  132","line":"    }","class":"lineCov","hits":"1","order":"1003",},
{"lineNum":"  133","line":""},
{"lineNum":"  134","line":"  private:"},
{"lineNum":"  135","line":"    stdx::option<buffer_pool<PoolSize>&> pool_;"},
{"lineNum":"  136","line":"    stdx::option<page&>                  pg_;"},
{"lineNum":"  137","line":"    bool                                 dirty_{false};","class":"lineCov","hits":"1","order":"1015",},
{"lineNum":"  138","line":"};"},
{"lineNum":"  139","line":""},
{"lineNum":"  140","line":"// Manager and dispatcher of concurrent frames from a disk manager."},
{"lineNum":"  141","line":"template <usize PoolSize> class buffer_pool {"},
{"lineNum":"  142","line":"  public:"},
{"lineNum":"  143","line":"    using read_guard_t  = read_guard<PoolSize>;"},
{"lineNum":"  144","line":"    using write_guard_t = write_guard<PoolSize>;"},
{"lineNum":"  145","line":"    static constexpr auto pool_size{PoolSize};"},
{"lineNum":"  146","line":""},
{"lineNum":"  147","line":"  public:"},
{"lineNum":"  148","line":"    explicit buffer_pool(stdx::box<disk_manager> dm) : disk_{std::move(dm)} {","class":"lineCov","hits":"1","order":"1112",},
{"lineNum":"  149","line":"        frames_ = stdx::make_box<page[]>(PoolSize);","class":"lineCov","hits":"1","order":"1109",},
{"lineNum":"  150","line":"        for (usize i{0}; i < PoolSize; ++i) {","class":"lineCov","hits":"1","order":"1106",},
{"lineNum":"  151","line":"            free_list_.emplace_back(static_cast<frame_id_t>(PoolSize - 1 - i));","class":"lineCov","hits":"1","order":"1102",},
{"lineNum":"  152","line":"        }","class":"lineCov","hits":"1","order":"1098",},
{"lineNum":"  153","line":"    }","class":"lineCov","hits":"1","order":"1096",},
{"lineNum":"  154","line":"    ~buffer_pool() { VERIFY(flush()); }","class":"lineCov","hits":"1","order":"1092",},
{"lineNum":"  155","line":"    MAKE_PINNED(buffer_pool);"},
{"lineNum":"  156","line":""},
{"lineNum":"  157","line":"    [[nodiscard]] static auto open(const std::filesystem::path& path)"},
{"lineNum":"  158","line":"        -> result<stdx::box<buffer_pool>> {","class":"lineCov","hits":"1","order":"1165",},
{"lineNum":"  159","line":"        auto dm{TRY(disk_manager::open(path))};","class":"lineCov","hits":"1","order":"1161",},
{"lineNum":"  160","line":"        return stdx::make_box<buffer_pool>(std::move(dm));","class":"lineCov","hits":"1","order":"1157",},
{"lineNum":"  161","line":"    }","class":"lineCov","hits":"1","order":"1148",},
{"lineNum":"  162","line":""},
{"lineNum":"  163","line":"    auto set_log_manager(stdx::option<wal::log::manager&> log) noexcept -> void { log_ = log; }"},
{"lineNum":"  164","line":""},
{"lineNum":"  165","line":"    auto snapshot_dpt(std::vector<wal::checkpoint::dpt_entry>& buf) noexcept -> void {"},
{"lineNum":"  166","line":"        std::scoped_lock lock{mutex_};"},
{"lineNum":"  167","line":"        buf.clear();"},
{"lineNum":"  168","line":"        buf.reserve(PoolSize);"},
{"lineNum":"  169","line":""},
{"lineNum":"  170","line":"        for (usize i{0}; i < PoolSize; ++i) {"},
{"lineNum":"  171","line":"            const auto& f{frame_at(static_cast<frame_id_t>(i))};"},
{"lineNum":"  172","line":"            if (f.is_dirty() && f.rec_lsn()) { buf.emplace_back(f.page_id(), *f.rec_lsn()); }"},
{"lineNum":"  173","line":"        }"},
{"lineNum":"  174","line":"    }"},
{"lineNum":"  175","line":""},
{"lineNum":"  176","line":"    [[nodiscard]] auto num_pages() const noexcept { return disk_->num_pages(); }"},
{"lineNum":"  177","line":""},
{"lineNum":"  178","line":"    // Pins the provided pid and returns a stable pointer"},
{"lineNum":"  179","line":"    [[nodiscard]] auto fetch_page(page_id_t pid) -> result<gsl::not_null<page*>> {","class":"lineCov","hits":"1","order":"1085",},
{"lineNum":"  180","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"1083",},
{"lineNum":"  181","line":""},
{"lineNum":"  182","line":"        if (auto slot{page_table_.get_opt(pid)}) {","class":"lineCov","hits":"1","order":"1080",},
{"lineNum":"  183","line":"            const auto fid{*slot};","class":"lineCov","hits":"1","order":"1078",},
{"lineNum":"  184","line":"            auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"1075",},
{"lineNum":"  185","line":"            if (f.is_deleted()) { return stdx::err{error::STORAGE_PAGE_NOT_FOUND}; }","class":"lineCov","hits":"1","order":"1072",},
{"lineNum":"  186","line":"            f.pin();","class":"lineCov","hits":"1","order":"1069",},
{"lineNum":"  187","line":"            replacer_.access(fid);","class":"lineCov","hits":"1","order":"1077",},
{"lineNum":"  188","line":"            replacer_.set_evictable(fid, false);","class":"lineCov","hits":"1","order":"1074",},
{"lineNum":"  189","line":"            return &f;","class":"lineCov","hits":"1","order":"1071",},
{"lineNum":"  190","line":"        }"},
{"lineNum":"  191","line":""},
{"lineNum":"  192","line":"        const auto fid{TRY(grab_victim_frame())};","class":"lineCov","hits":"1","order":"1068",},
{"lineNum":"  193","line":"        auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"1066",},
{"lineNum":"  194","line":"        f.reset(pid, false);","class":"lineCov","hits":"1","order":"1065",},
{"lineNum":"  195","line":""},
{"lineNum":"  196","line":"        if (auto r{disk_->read_page(pid, f.data())}; !r) {","class":"lineCov","hits":"1","order":"1064",},
{"lineNum":"  197","line":"            free_list_.emplace_back(fid);","class":"lineNoCov","hits":"0",},
{"lineNum":"  198","line":"            return stdx::err{r.error()};","class":"lineNoCov","hits":"0",},
{"lineNum":"  199","line":"        }"},
{"lineNum":"  200","line":""},
{"lineNum":"  201","line":"        f.pin();","class":"lineCov","hits":"1","order":"1062",},
{"lineNum":"  202","line":"        page_table_.emplace(pid, fid);","class":"lineCov","hits":"1","order":"1061",},
{"lineNum":"  203","line":"        replacer_.access(fid);","class":"lineCov","hits":"1","order":"1060",},
{"lineNum":"  204","line":"        replacer_.set_evictable(fid, false);","class":"lineCov","hits":"1","order":"1059",},
{"lineNum":"  205","line":"        return &f;","class":"lineCov","hits":"1","order":"1058",},
{"lineNum":"  206","line":"    }","class":"lineCov","hits":"1","order":"1067",},
{"lineNum":"  207","line":""},
{"lineNum":"  208","line":"    // Allocates a fresh zeroed page"},
{"lineNum":"  209","line":"    [[nodiscard]] auto new_page() -> result<gsl::not_null<page*>> {","class":"lineCov","hits":"1","order":"1158",},
{"lineNum":"  210","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"1152",},
{"lineNum":"  211","line":"        const auto       fid{TRY(grab_victim_frame())};","class":"lineCov","hits":"1","order":"1151",},
{"lineNum":"  212","line":""},
{"lineNum":"  213","line":"        auto pid{INVALID_PAGE_ID};","class":"lineCov","hits":"1","order":"1162",},
{"lineNum":"  214","line":"        if (!free_pages_.empty()) {","class":"lineCov","hits":"1","order":"1159",},
{"lineNum":"  215","line":"            pid = free_pages_.back();","class":"lineCov","hits":"1","order":"1154",},
{"lineNum":"  216","line":"            free_pages_.pop_back();","class":"lineCov","hits":"1","order":"1147",},
{"lineNum":"  217","line":"        } else {","class":"lineCov","hits":"1","order":"1146",},
{"lineNum":"  218","line":"            auto allocated{disk_->allocate_page()};","class":"lineCov","hits":"1","order":"1141",},
{"lineNum":"  219","line":"            if (!allocated) {","class":"lineCov","hits":"1","order":"1130",},
{"lineNum":"  220","line":"                free_list_.emplace_back(fid);","class":"lineNoCov","hits":"0",},
{"lineNum":"  221","line":"                return stdx::err{allocated.error()};","class":"lineNoCov","hits":"0",},
{"lineNum":"  222","line":"            }"},
{"lineNum":"  223","line":"            pid = *allocated;","class":"lineCov","hits":"1","order":"1140",},
{"lineNum":"  224","line":"        }"},
{"lineNum":"  225","line":""},
{"lineNum":"  226","line":"        auto& f{frame_at(fid)};","class":"lineCov","hits":"1","order":"1138",},
{"lineNum":"  227","line":"        f.reset(pid);","class":"lineCov","hits":"1","order":"1164",},
{"lineNum":"  228","line":""},
{"lineNum":"  229","line":"        f.set_dirty(true);","class":"lineCov","hits":"1","order":"1155",},
{"lineNum":"  230","line":"        f.pin();","class":"lineCov","hits":"1","order":"1153",},
{"lineNum":"  231","line":"        page_table_.emplace(pid, fid);","class":"lineCov","hits":"1","order":"1137",},
{"lineNum":"  232","line":"        replacer_.access(fid);","class":"lineCov","hits":"1","order":"1136",},
{"lineNum":"  233","line":"        replacer_.set_evictable(fid, false);","class":"lineCov","hits":"1","order":"1134",},
{"lineNum":"  234","line":"        return &f;","class":"lineCov","hits":"1","order":"1132",},
{"lineNum":"  235","line":"    }","class":"lineCov","hits":"1","order":"1163",},
{"lineNum":"  236","line":""},
{"lineNum":"  237","line":"    [[nodiscard]] auto unpin_page(page_id_t pid, bool dirty) -> result<void> {","class":"lineCov","hits":"1","order":"1126",},
{"lineNum":"  238","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"1125",},
{"lineNum":"  239","line":"        auto             slot{page_table_.get_opt(pid)};","class":"lineCov","hits":"1","order":"1123",},
{"lineNum":"  240","line":"        if (!slot) { return stdx::err{error::STORAGE_PAGE_NOT_FOUND}; }","class":"lineCov","hits":"1","order":"1121",},
{"lineNum":"  241","line":""},
{"lineNum":"  242","line":"        const auto fid{*slot};","class":"lineCov","hits":"1","order":"1119",},
{"lineNum":"  243","line":"        auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"1118",},
{"lineNum":"  244","line":"        if (f.pin_count() <= 0) { return stdx::err{error::STORAGE_PAGE_NOT_FOUND}; }","class":"lineCov","hits":"1","order":"1116",},
{"lineNum":"  245","line":"        if (dirty) { f.set_dirty(true); }","class":"lineCov","hits":"1","order":"1114",},
{"lineNum":"  246","line":"        if (f.unpin() == 0) {","class":"lineCov","hits":"1","order":"1111",},
{"lineNum":"  247","line":"            if (f.is_deleted()) {","class":"lineCov","hits":"1","order":"1108",},
{"lineNum":"  248","line":"                page_table_.remove(pid);","class":"lineCov","hits":"1","order":"1104",},
{"lineNum":"  249","line":"                replacer_.remove(fid);","class":"lineCov","hits":"1","order":"1100",},
{"lineNum":"  250","line":"                f.reset(INVALID_PAGE_ID, true);","class":"lineCov","hits":"1","order":"1097",},
{"lineNum":"  251","line":"                free_list_.emplace_back(fid);","class":"lineCov","hits":"1","order":"1094",},
{"lineNum":"  252","line":"                free_pages_.emplace_back(pid);","class":"lineCov","hits":"1","order":"1090",},
{"lineNum":"  253","line":"            } else {","class":"lineCov","hits":"1","order":"1089",},
{"lineNum":"  254","line":"                replacer_.set_evictable(fid, true);","class":"lineCov","hits":"1","order":"1088",},
{"lineNum":"  255","line":"            }"},
{"lineNum":"  256","line":"        }","class":"lineCov","hits":"1","order":"1160",},
{"lineNum":"  257","line":"        return {};","class":"lineCov","hits":"1","order":"1156",},
{"lineNum":"  258","line":"    }","class":"lineCov","hits":"1","order":"1150",},
{"lineNum":"  259","line":""},
{"lineNum":"  260","line":"    // Flush a specific frame in the pool"},
{"lineNum":"  261","line":"    [[nodiscard]] auto flush(page_id_t pid) -> result<void> {"},
{"lineNum":"  262","line":"        std::scoped_lock lock{mutex_};"},
{"lineNum":"  263","line":"        auto             slot{page_table_.get_opt(pid)};"},
{"lineNum":"  264","line":"        if (!slot) { return stdx::err{error::STORAGE_PAGE_NOT_FOUND}; }"},
{"lineNum":"  265","line":"        return flush_locked(*slot);"},
{"lineNum":"  266","line":"    }"},
{"lineNum":"  267","line":""},
{"lineNum":"  268","line":"    // Flushes all frames in the buffer"},
{"lineNum":"  269","line":"    [[nodiscard]] auto flush() -> result<void> {","class":"lineCov","hits":"1","order":"1057",},
{"lineNum":"  270","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"1055",},
{"lineNum":"  271","line":"        for (usize i{0}; i < PoolSize; ++i) { TRY(flush_locked(static_cast<frame_id_t>(i))); }","class":"lineCov","hits":"1","order":"1053",},
{"lineNum":"  272","line":"        return {};","class":"lineCov","hits":"1","order":"1049",},
{"lineNum":"  273","line":"    }","class":"lineCov","hits":"1","order":"1051",},
{"lineNum":"  274","line":""},
{"lineNum":"  275","line":"    // Evicts the provides pid unless it isn\'t resident in which case this is a noop"},
{"lineNum":"  276","line":"    [[nodiscard]] auto delete_page(page_id_t pid) -> result<void> {","class":"lineCov","hits":"1","order":"990",},
{"lineNum":"  277","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"989",},
{"lineNum":"  278","line":"        auto             slot{page_table_.get_opt(pid)};","class":"lineCov","hits":"1","order":"988",},
{"lineNum":"  279","line":"        if (!slot) { return {}; }","class":"lineCov","hits":"1","order":"987",},
{"lineNum":"  280","line":""},
{"lineNum":"  281","line":"        const auto fid{*slot};","class":"lineCov","hits":"1","order":"986",},
{"lineNum":"  282","line":"        auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"985",},
{"lineNum":"  283","line":"        if (f.pin_count() > 0) {","class":"lineCov","hits":"1","order":"984",},
{"lineNum":"  284","line":"            f.set_deleted(true);","class":"lineCov","hits":"1","order":"983",},
{"lineNum":"  285","line":"            return {};","class":"lineCov","hits":"1","order":"992",},
{"lineNum":"  286","line":"        }"},
{"lineNum":"  287","line":""},
{"lineNum":"  288","line":"        page_table_.remove(pid);","class":"lineCov","hits":"1","order":"982",},
{"lineNum":"  289","line":"        replacer_.remove(fid);","class":"lineCov","hits":"1","order":"981",},
{"lineNum":"  290","line":"        f.reset(INVALID_PAGE_ID, true);","class":"lineCov","hits":"1","order":"980",},
{"lineNum":"  291","line":"        free_list_.emplace_back(fid);","class":"lineCov","hits":"1","order":"979",},
{"lineNum":"  292","line":"        free_pages_.emplace_back(pid);","class":"lineCov","hits":"1","order":"978",},
{"lineNum":"  293","line":"        return {};","class":"lineCov","hits":"1","order":"977",},
{"lineNum":"  294","line":"    }","class":"lineCov","hits":"1","order":"976",},
{"lineNum":"  295","line":""},
{"lineNum":"  296","line":"    [[nodiscard]] auto fetch_read(page_id_t pid) -> result<read_guard_t> {","class":"lineCov","hits":"1","order":"1024",},
{"lineNum":"  297","line":"        auto pg{TRY(fetch_page(pid))};","class":"lineCov","hits":"1","order":"1022",},
{"lineNum":"  298","line":"        pg->latch().lock_shared();","class":"lineCov","hits":"1","order":"1021",},
{"lineNum":"  299","line":"        return read_guard_t{*this, *pg};","class":"lineCov","hits":"1","order":"1020",},
{"lineNum":"  300","line":"    }","class":"lineCov","hits":"1","order":"1019",},
{"lineNum":"  301","line":""},
{"lineNum":"  302","line":"    [[nodiscard]] auto fetch_write(page_id_t pid) -> result<write_guard_t> {","class":"lineCov","hits":"1","order":"998",},
{"lineNum":"  303","line":"        auto pg{TRY(fetch_page(pid))};","class":"lineCov","hits":"1","order":"997",},
{"lineNum":"  304","line":"        pg->latch().lock();","class":"lineCov","hits":"1","order":"996",},
{"lineNum":"  305","line":"        return write_guard_t{*this, *pg};","class":"lineCov","hits":"1","order":"995",},
{"lineNum":"  306","line":"    }","class":"lineCov","hits":"1","order":"994",},
{"lineNum":"  307","line":""},
{"lineNum":"  308","line":"    [[nodiscard]] auto new_write() -> result<std::pair<page_id_t, write_guard_t>> {","class":"lineCov","hits":"1","order":"1031",},
{"lineNum":"  309","line":"        auto pg{TRY(new_page())};","class":"lineCov","hits":"1","order":"1030",},
{"lineNum":"  310","line":"        pg->latch().lock();","class":"lineCov","hits":"1","order":"1029",},
{"lineNum":"  311","line":"        return std::make_pair(pg->page_id(), write_guard_t{*this, *pg});","class":"lineCov","hits":"1","order":"1028",},
{"lineNum":"  312","line":"    }","class":"lineCov","hits":"1","order":"1026",},
{"lineNum":"  313","line":""},
{"lineNum":"  314","line":"    [[nodiscard]] auto pin_count(page_id_t pid) -> stdx::option<i32> {","class":"lineCov","hits":"1","order":"1145",},
{"lineNum":"  315","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"1143",},
{"lineNum":"  316","line":"        auto             slot{page_table_.get_opt(pid)};","class":"lineCov","hits":"1","order":"1131",},
{"lineNum":"  317","line":"        if (!slot) { return stdx::none; }","class":"lineCov","hits":"1","order":"1139",},
{"lineNum":"  318","line":"        return frame_at(*slot).pin_count();","class":"lineCov","hits":"1","order":"1129",},
{"lineNum":"  319","line":"    }","class":"lineCov","hits":"1","order":"1127",},
{"lineNum":"  320","line":""},
{"lineNum":"  321","line":"    [[nodiscard]] auto is_resident(page_id_t pid) -> bool {"},
{"lineNum":"  322","line":"        std::scoped_lock lock{mutex_};"},
{"lineNum":"  323","line":"        return page_table_.contains(pid);"},
{"lineNum":"  324","line":"    }"},
{"lineNum":"  325","line":""},
{"lineNum":"  326","line":"    [[nodiscard]] auto evictable_count() -> usize {"},
{"lineNum":"  327","line":"        std::scoped_lock lock{mutex_};"},
{"lineNum":"  328","line":"        return replacer_.size();"},
{"lineNum":"  329","line":"    }"},
{"lineNum":"  330","line":""},
{"lineNum":"  331","line":"  private:"},
{"lineNum":"  332","line":"    static constexpr usize TABLE_CAPACITY{PoolSize * 2};"},
{"lineNum":"  333","line":""},
{"lineNum":"  334","line":"  private:"},
{"lineNum":"  335","line":"    [[nodiscard]] auto frame_at(frame_id_t fid) noexcept -> page& {","class":"lineCov","hits":"1","order":"1047",},
{"lineNum":"  336","line":"        return frames_[static_cast<usize>(std::to_underlying(fid))];","class":"lineCov","hits":"1","order":"1046",},
{"lineNum":"  337","line":"    }"},
{"lineNum":"  338","line":""},
{"lineNum":"  339","line":"    // Caller needs to hold the mutex"},
{"lineNum":"  340","line":"    [[nodiscard]] auto grab_victim_frame() -> result<frame_id_t> {","class":"lineCov","hits":"1","order":"1045",},
{"lineNum":"  341","line":"        if (!free_list_.empty()) {","class":"lineCov","hits":"1","order":"1044",},
{"lineNum":"  342","line":"            const auto fid{free_list_.back()};","class":"lineCov","hits":"1","order":"1043",},
{"lineNum":"  343","line":"            free_list_.pop_back();","class":"lineCov","hits":"1","order":"1042",},
{"lineNum":"  344","line":"            return fid;","class":"lineCov","hits":"1","order":"1041",},
{"lineNum":"  345","line":"        }"},
{"lineNum":"  346","line":""},
{"lineNum":"  347","line":"        auto victim{replacer_.evict()};","class":"lineCov","hits":"1","order":"1105",},
{"lineNum":"  348","line":"        if (!victim) { return stdx::err{error::STORAGE_POOL_EXHAUSTED}; }","class":"lineCov","hits":"1","order":"1101",},
{"lineNum":"  349","line":""},
{"lineNum":"  350","line":"        const auto fid{*victim};","class":"lineCov","hits":"1","order":"1095",},
{"lineNum":"  351","line":"        auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"1091",},
{"lineNum":"  352","line":"        if (f.is_dirty()) {","class":"lineCov","hits":"1","order":"1040",},
{"lineNum":"  353","line":"            if (auto lsn{f.page_lsn()}; log_ && lsn) {","class":"lineCov","hits":"1","order":"1039",},
{"lineNum":"  354","line":"                if (auto r{log_->flush(*lsn)}; !r) {","class":"lineNoCov","hits":"0",},
{"lineNum":"  355","line":"                    replacer_.access(fid);","class":"lineNoCov","hits":"0",},
{"lineNum":"  356","line":"                    replacer_.set_evictable(fid, true);","class":"lineNoCov","hits":"0",},
{"lineNum":"  357","line":"                    return stdx::err{r.error()};","class":"lineNoCov","hits":"0",},
{"lineNum":"  358","line":"                }"},
{"lineNum":"  359","line":"            }","class":"lineNoCov","hits":"0",},
{"lineNum":"  360","line":"            // If the frame cannot persist then it must stay resident"},
{"lineNum":"  361","line":"            if (auto r{disk_->write_page(f.page_id(), f.data())}; !r) {","class":"lineCov","hits":"1","order":"1038",},
{"lineNum":"  362","line":"                replacer_.access(fid);","class":"lineNoCov","hits":"0",},
{"lineNum":"  363","line":"                replacer_.set_evictable(fid, true);","class":"lineNoCov","hits":"0",},
{"lineNum":"  364","line":"                return stdx::err{r.error()};","class":"lineNoCov","hits":"0",},
{"lineNum":"  365","line":"            }"},
{"lineNum":"  366","line":"            f.set_dirty(false);","class":"lineCov","hits":"1","order":"1037",},
{"lineNum":"  367","line":"            f.set_page_lsn(stdx::none);","class":"lineCov","hits":"1","order":"1036",},
{"lineNum":"  368","line":"            f.clear_rec_lsn();","class":"lineCov","hits":"1","order":"1035",},
{"lineNum":"  369","line":"        }"},
{"lineNum":"  370","line":"        page_table_.remove(f.page_id());","class":"lineCov","hits":"1","order":"1034",},
{"lineNum":"  371","line":"        return fid;","class":"lineCov","hits":"1","order":"1033",},
{"lineNum":"  372","line":"    }","class":"lineCov","hits":"1","order":"1032",},
{"lineNum":"  373","line":""},
{"lineNum":"  374","line":"    [[nodiscard]] auto flush_locked(frame_id_t fid) -> result<void> {","class":"lineCov","hits":"1","order":"1087",},
{"lineNum":"  375","line":"        auto& f{frame_at(fid)};","class":"lineCov","hits":"1","order":"1048",},
{"lineNum":"  376","line":"        if (!f.is_dirty()) { return {}; }","class":"lineCov","hits":"1","order":"1086",},
{"lineNum":"  377","line":"        if (auto lsn{f.page_lsn()}; log_ && lsn) { TRY(log_->flush(*lsn)); }","class":"lineCov","hits":"1","order":"1084",},
{"lineNum":"  378","line":"        TRY(disk_->write_page(f.page_id(), f.data()));","class":"lineCov","hits":"1","order":"1082",},
{"lineNum":"  379","line":"        f.set_dirty(false);","class":"lineCov","hits":"1","order":"1081",},
{"lineNum":"  380","line":"        f.set_page_lsn(stdx::none);","class":"lineCov","hits":"1","order":"1079",},
{"lineNum":"  381","line":"        f.clear_rec_lsn();","class":"lineCov","hits":"1","order":"1076",},
{"lineNum":"  382","line":"        return {};","class":"lineCov","hits":"1","order":"1073",},
{"lineNum":"  383","line":"    }","class":"lineCov","hits":"1","order":"1070",},
{"lineNum":"  384","line":""},
{"lineNum":"  385","line":"  private:"},
{"lineNum":"  386","line":"    std::mutex                                                        mutex_;"},
{"lineNum":"  387","line":"    stdx::box<disk_manager>                                           disk_;"},
{"lineNum":"  388","line":"    stdx::box<page[]>                                                 frames_;"},
{"lineNum":"  389","line":"    frame_replacer<PoolSize>                                          replacer_;"},
{"lineNum":"  390","line":"    stdx::fixed::vector<frame_id_t, PoolSize>                         free_list_;"},
{"lineNum":"  391","line":"    std::vector<page_id_t>                                            free_pages_;"},
{"lineNum":"  392","line":"    usize                                                             page_table_churn_{0};","class":"lineCov","hits":"1","order":"1063",},
{"lineNum":"  393","line":"    stdx::fixed::auto_hash_map<page_id_t, frame_id_t, TABLE_CAPACITY> page_table_;"},
{"lineNum":"  394","line":""},
{"lineNum":"  395","line":"    stdx::option<wal::log::manager&> log_;"},
{"lineNum":"  396","line":"};"},
{"lineNum":"  397","line":""},
{"lineNum":"  398","line":"} // namespace cairn::storage"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-07-24 01:31:31", "instrumented" : 202, "covered" : 190,};
var merged_data = [];
