var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include <filesystem>"},
{"lineNum":"    4","line":"#include <mutex>"},
{"lineNum":"    5","line":"#include <utility>"},
{"lineNum":"    6","line":"#include <vector>"},
{"lineNum":"    7","line":""},
{"lineNum":"    8","line":"#include <gsl/pointers>"},
{"lineNum":"    9","line":"#include <stdx/assert.hh>"},
{"lineNum":"   10","line":"#include <stdx/fixed/hash_table.hh>"},
{"lineNum":"   11","line":"#include <stdx/fixed/vector.hh>"},
{"lineNum":"   12","line":"#include <stdx/memory.hh>"},
{"lineNum":"   13","line":"#include <stdx/option.hh>"},
{"lineNum":"   14","line":"#include <stdx/result.hh>"},
{"lineNum":"   15","line":"#include <stdx/types.hh>"},
{"lineNum":"   16","line":"#include <stdx/utility.hh>"},
{"lineNum":"   17","line":""},
{"lineNum":"   18","line":"#include \"storage/disk_manager.hh\""},
{"lineNum":"   19","line":"#include \"storage/error.hh\""},
{"lineNum":"   20","line":"#include \"storage/frame_replacer.hh\""},
{"lineNum":"   21","line":"#include \"storage/page.hh\""},
{"lineNum":"   22","line":""},
{"lineNum":"   23","line":"namespace cairn::storage {"},
{"lineNum":"   24","line":""},
{"lineNum":"   25","line":"template <usize PoolSize> class buffer_pool;"},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"// RAII holding a shared latch on a pinned page"},
{"lineNum":"   28","line":"template <usize PoolSize>"},
{"lineNum":"   29","line":"    requires(PoolSize > 0)"},
{"lineNum":"   30","line":"class read_guard {"},
{"lineNum":"   31","line":"  public:"},
{"lineNum":"   32","line":"    constexpr read_guard() noexcept = default;"},
{"lineNum":"   33","line":"    read_guard(buffer_pool<PoolSize>& pool, page& pg) noexcept : pool_{pool}, pg_{pg} {}","class":"lineCov","hits":"1","order":"826",},
{"lineNum":"   34","line":"    ~read_guard() { drop(); }","class":"lineCov","hits":"1","order":"845",},
{"lineNum":"   35","line":""},
{"lineNum":"   36","line":"    read_guard(const read_guard&)                    = delete;"},
{"lineNum":"   37","line":"    auto operator=(const read_guard&) -> read_guard& = delete;"},
{"lineNum":"   38","line":""},
{"lineNum":"   39","line":"    read_guard(read_guard&& other) noexcept : pool_{other.pool_}, pg_{other.pg_} {","class":"lineCov","hits":"1","order":"846",},
{"lineNum":"   40","line":"        other.pool_.reset();","class":"lineCov","hits":"1","order":"957",},
{"lineNum":"   41","line":"        other.pg_.reset();","class":"lineCov","hits":"1","order":"954",},
{"lineNum":"   42","line":"    }","class":"lineCov","hits":"1","order":"946",},
{"lineNum":"   43","line":""},
{"lineNum":"   44","line":"    auto operator=(read_guard&& other) noexcept -> read_guard& {","class":"lineCov","hits":"1","order":"949",},
{"lineNum":"   45","line":"        if (this != &other) {","class":"lineCov","hits":"1","order":"821",},
{"lineNum":"   46","line":"            drop();","class":"lineCov","hits":"1","order":"820",},
{"lineNum":"   47","line":"            pool_ = other.pool_;","class":"lineCov","hits":"1","order":"819",},
{"lineNum":"   48","line":"            pg_   = other.pg_;","class":"lineCov","hits":"1","order":"817",},
{"lineNum":"   49","line":"            other.pool_.reset();","class":"lineCov","hits":"1","order":"815",},
{"lineNum":"   50","line":"            other.pg_.reset();","class":"lineCov","hits":"1","order":"813",},
{"lineNum":"   51","line":"        }"},
{"lineNum":"   52","line":"        return *this;","class":"lineCov","hits":"1","order":"811",},
{"lineNum":"   53","line":"    }"},
{"lineNum":"   54","line":""},
{"lineNum":"   55","line":"    [[nodiscard]] auto valid() const noexcept -> bool { return pool_.has_value(); }"},
{"lineNum":"   56","line":"    [[nodiscard]] auto page_id() const noexcept -> page_id_t { return pg_->page_id(); }"},
{"lineNum":"   57","line":""},
{"lineNum":"   58","line":"    // Read-only view of the page\'s bytes"},
{"lineNum":"   59","line":"    template <typename T> [[nodiscard]] auto as() const noexcept -> gsl::not_null<const T*> {","class":"lineCov","hits":"1","order":"931",},
{"lineNum":"   60","line":"        return stdx::object_at<T>(pg_->data());","class":"lineCov","hits":"1","order":"926",},
{"lineNum":"   61","line":"    }"},
{"lineNum":"   62","line":""},
{"lineNum":"   63","line":"    // Called automatically on destruction but safe to call manually"},
{"lineNum":"   64","line":"    auto drop() noexcept -> void {","class":"lineCov","hits":"1","order":"825",},
{"lineNum":"   65","line":"        if (pool_) {","class":"lineCov","hits":"1","order":"855",},
{"lineNum":"   66","line":"            const auto pid{pg_->page_id()};","class":"lineCov","hits":"1","order":"853",},
{"lineNum":"   67","line":"            pg_->latch().unlock_shared();","class":"lineCov","hits":"1","order":"851",},
{"lineNum":"   68","line":"            DISCARD(pool_->unpin_page(pid, false));","class":"lineCov","hits":"1","order":"849",},
{"lineNum":"   69","line":"            pool_.reset();","class":"lineCov","hits":"1","order":"847",},
{"lineNum":"   70","line":"            pg_.reset();","class":"lineCov","hits":"1","order":"824",},
{"lineNum":"   71","line":"        }"},
{"lineNum":"   72","line":"    }","class":"lineCov","hits":"1","order":"823",},
{"lineNum":"   73","line":""},
{"lineNum":"   74","line":"  private:"},
{"lineNum":"   75","line":"    stdx::option<buffer_pool<PoolSize>&> pool_;"},
{"lineNum":"   76","line":"    stdx::option<page&>                  pg_;"},
{"lineNum":"   77","line":"};"},
{"lineNum":"   78","line":""},
{"lineNum":"   79","line":"// RAII holding an exclusive latch on a pinned page"},
{"lineNum":"   80","line":"template <usize PoolSize>"},
{"lineNum":"   81","line":"    requires(PoolSize > 0)"},
{"lineNum":"   82","line":"class write_guard {"},
{"lineNum":"   83","line":"  public:"},
{"lineNum":"   84","line":"    constexpr write_guard() noexcept = default;","class":"lineCov","hits":"1","order":"805",},
{"lineNum":"   85","line":"    write_guard(buffer_pool<PoolSize>& pool, page& pg) noexcept : pool_{pool}, pg_{pg} {}","class":"lineCov","hits":"1","order":"894",},
{"lineNum":"   86","line":"    ~write_guard() { drop(); }","class":"lineCov","hits":"1","order":"892",},
{"lineNum":"   87","line":""},
{"lineNum":"   88","line":"    write_guard(const write_guard&)                    = delete;"},
{"lineNum":"   89","line":"    auto operator=(const write_guard&) -> write_guard& = delete;"},
{"lineNum":"   90","line":""},
{"lineNum":"   91","line":"    write_guard(write_guard&& other) noexcept"},
{"lineNum":"   92","line":"        : pool_{other.pool_}, pg_{other.pg_}, dirty_{other.dirty_} {","class":"lineCov","hits":"1","order":"960",},
{"lineNum":"   93","line":"        other.pool_.reset();","class":"lineCov","hits":"1","order":"874",},
{"lineNum":"   94","line":"        other.pg_.reset();","class":"lineCov","hits":"1","order":"951",},
{"lineNum":"   95","line":"    }","class":"lineCov","hits":"1","order":"941",},
{"lineNum":"   96","line":""},
{"lineNum":"   97","line":"    auto operator=(write_guard&& other) noexcept -> write_guard& {"},
{"lineNum":"   98","line":"        if (this != &other) {"},
{"lineNum":"   99","line":"            drop();"},
{"lineNum":"  100","line":"            pool_  = other.pool_;"},
{"lineNum":"  101","line":"            pg_    = other.pg_;"},
{"lineNum":"  102","line":"            dirty_ = other.dirty_;"},
{"lineNum":"  103","line":"            other.pool_.reset();"},
{"lineNum":"  104","line":"            other.pg_.reset();"},
{"lineNum":"  105","line":"        }"},
{"lineNum":"  106","line":"        return *this;"},
{"lineNum":"  107","line":"    }"},
{"lineNum":"  108","line":""},
{"lineNum":"  109","line":"    [[nodiscard]] auto valid() const noexcept -> bool { return pool_.has_value(); }"},
{"lineNum":"  110","line":"    [[nodiscard]] auto page_id() const noexcept -> page_id_t { return pg_->page_id(); }","class":"lineCov","hits":"1","order":"967",},
{"lineNum":"  111","line":"    auto               mark_dirty() noexcept -> void { dirty_ = true; }","class":"lineCov","hits":"1","order":"918",},
{"lineNum":"  112","line":""},
{"lineNum":"  113","line":"    template <typename T> [[nodiscard]] auto as(this auto&& self) noexcept -> auto* {","class":"lineCov","hits":"1","order":"903",},
{"lineNum":"  114","line":"        return stdx::object_at<T>(self.pg_->data());","class":"lineCov","hits":"1","order":"889",},
{"lineNum":"  115","line":"    }"},
{"lineNum":"  116","line":""},
{"lineNum":"  117","line":"    // Called automatically on destruction but safe to call manually"},
{"lineNum":"  118","line":"    auto drop() noexcept -> void {","class":"lineCov","hits":"1","order":"873",},
{"lineNum":"  119","line":"        if (pool_) {","class":"lineCov","hits":"1","order":"871",},
{"lineNum":"  120","line":"            const auto pid{pg_->page_id()};","class":"lineCov","hits":"1","order":"887",},
{"lineNum":"  121","line":"            pg_->latch().unlock();","class":"lineCov","hits":"1","order":"883",},
{"lineNum":"  122","line":"            DISCARD(pool_->unpin_page(pid, dirty_));","class":"lineCov","hits":"1","order":"870",},
{"lineNum":"  123","line":"            pool_.reset();","class":"lineCov","hits":"1","order":"885",},
{"lineNum":"  124","line":"            pg_.reset();","class":"lineCov","hits":"1","order":"882",},
{"lineNum":"  125","line":"        }"},
{"lineNum":"  126","line":"    }","class":"lineCov","hits":"1","order":"868",},
{"lineNum":"  127","line":""},
{"lineNum":"  128","line":"  private:"},
{"lineNum":"  129","line":"    stdx::option<buffer_pool<PoolSize>&> pool_;"},
{"lineNum":"  130","line":"    stdx::option<page&>                  pg_;"},
{"lineNum":"  131","line":"    bool                                 dirty_{false};","class":"lineCov","hits":"1","order":"878",},
{"lineNum":"  132","line":"};"},
{"lineNum":"  133","line":""},
{"lineNum":"  134","line":"// Manager and dispatcher of concurrent frames from a disk manager."},
{"lineNum":"  135","line":"template <usize PoolSize> class buffer_pool {"},
{"lineNum":"  136","line":"  public:"},
{"lineNum":"  137","line":"    using read_guard_t  = read_guard<PoolSize>;"},
{"lineNum":"  138","line":"    using write_guard_t = write_guard<PoolSize>;"},
{"lineNum":"  139","line":"    static constexpr auto pool_size{PoolSize};"},
{"lineNum":"  140","line":""},
{"lineNum":"  141","line":"  public:"},
{"lineNum":"  142","line":"    explicit buffer_pool(stdx::box<disk_manager> dm) : disk_{std::move(dm)} {","class":"lineCov","hits":"1","order":"943",},
{"lineNum":"  143","line":"        frames_ = stdx::make_box<page[]>(PoolSize);","class":"lineCov","hits":"1","order":"938",},
{"lineNum":"  144","line":"        for (usize i{0}; i < PoolSize; ++i) {","class":"lineCov","hits":"1","order":"932",},
{"lineNum":"  145","line":"            free_list_.emplace_back(static_cast<frame_id_t>(PoolSize - 1 - i));","class":"lineCov","hits":"1","order":"928",},
{"lineNum":"  146","line":"        }","class":"lineCov","hits":"1","order":"936",},
{"lineNum":"  147","line":"    }","class":"lineCov","hits":"1","order":"923",},
{"lineNum":"  148","line":"    ~buffer_pool() { VERIFY(flush()); }","class":"lineCov","hits":"1","order":"921",},
{"lineNum":"  149","line":"    MAKE_PINNED(buffer_pool);"},
{"lineNum":"  150","line":""},
{"lineNum":"  151","line":"    [[nodiscard]] static auto open(const std::filesystem::path& path)"},
{"lineNum":"  152","line":"        -> result<stdx::box<buffer_pool>> {","class":"lineCov","hits":"1","order":"919",},
{"lineNum":"  153","line":"        auto dm{TRY(disk_manager::open(path))};","class":"lineCov","hits":"1","order":"914",},
{"lineNum":"  154","line":"        return stdx::make_box<buffer_pool>(std::move(dm));","class":"lineCov","hits":"1","order":"927",},
{"lineNum":"  155","line":"    }","class":"lineCov","hits":"1","order":"959",},
{"lineNum":"  156","line":""},
{"lineNum":"  157","line":"    // Pins the provided pid and returns a stable pointer"},
{"lineNum":"  158","line":"    [[nodiscard]] auto fetch_page(page_id_t pid) -> result<gsl::not_null<page*>> {","class":"lineCov","hits":"1","order":"844",},
{"lineNum":"  159","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"962",},
{"lineNum":"  160","line":""},
{"lineNum":"  161","line":"        if (auto slot{page_table_.get_opt(pid)}) {","class":"lineCov","hits":"1","order":"843",},
{"lineNum":"  162","line":"            const auto fid{*slot};","class":"lineCov","hits":"1","order":"842",},
{"lineNum":"  163","line":"            auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"841",},
{"lineNum":"  164","line":"            f.pin();","class":"lineCov","hits":"1","order":"840",},
{"lineNum":"  165","line":"            replacer_.access(fid);","class":"lineCov","hits":"1","order":"839",},
{"lineNum":"  166","line":"            replacer_.set_evictable(fid, false);","class":"lineCov","hits":"1","order":"838",},
{"lineNum":"  167","line":"            return &f;","class":"lineCov","hits":"1","order":"837",},
{"lineNum":"  168","line":"        }"},
{"lineNum":"  169","line":""},
{"lineNum":"  170","line":"        const auto fid{TRY(grab_victim_frame())};","class":"lineCov","hits":"1","order":"836",},
{"lineNum":"  171","line":"        auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"834",},
{"lineNum":"  172","line":"        f.reset(pid);","class":"lineCov","hits":"1","order":"833",},
{"lineNum":"  173","line":""},
{"lineNum":"  174","line":"        if (auto r{disk_->read_page(pid, f.data())}; !r) {","class":"lineCov","hits":"1","order":"832",},
{"lineNum":"  175","line":"            free_list_.emplace_back(fid);","class":"lineNoCov","hits":"0",},
{"lineNum":"  176","line":"            return stdx::err{r.error()};","class":"lineNoCov","hits":"0",},
{"lineNum":"  177","line":"        }"},
{"lineNum":"  178","line":""},
{"lineNum":"  179","line":"        f.pin();","class":"lineCov","hits":"1","order":"831",},
{"lineNum":"  180","line":"        page_table_.emplace(pid, fid);","class":"lineCov","hits":"1","order":"830",},
{"lineNum":"  181","line":"        replacer_.access(fid);","class":"lineCov","hits":"1","order":"829",},
{"lineNum":"  182","line":"        replacer_.set_evictable(fid, false);","class":"lineCov","hits":"1","order":"828",},
{"lineNum":"  183","line":"        return &f;","class":"lineCov","hits":"1","order":"827",},
{"lineNum":"  184","line":"    }","class":"lineCov","hits":"1","order":"835",},
{"lineNum":"  185","line":""},
{"lineNum":"  186","line":"    // Allocates a fresh zeroed page"},
{"lineNum":"  187","line":"    [[nodiscard]] auto new_page() -> result<gsl::not_null<page*>> {","class":"lineCov","hits":"1","order":"907",},
{"lineNum":"  188","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"906",},
{"lineNum":"  189","line":"        const auto       fid{TRY(grab_victim_frame())};","class":"lineCov","hits":"1","order":"961",},
{"lineNum":"  190","line":""},
{"lineNum":"  191","line":"        auto pid{INVALID_PAGE_ID};","class":"lineCov","hits":"1","order":"952",},
{"lineNum":"  192","line":"        if (!free_pages_.empty()) {","class":"lineCov","hits":"1","order":"942",},
{"lineNum":"  193","line":"            pid = free_pages_.back();","class":"lineCov","hits":"1","order":"934",},
{"lineNum":"  194","line":"            free_pages_.pop_back();","class":"lineCov","hits":"1","order":"948",},
{"lineNum":"  195","line":"        } else {","class":"lineCov","hits":"1","order":"940",},
{"lineNum":"  196","line":"            auto allocated{disk_->allocate_page()};","class":"lineCov","hits":"1","order":"902",},
{"lineNum":"  197","line":"            if (!allocated) {","class":"lineCov","hits":"1","order":"901",},
{"lineNum":"  198","line":"                free_list_.emplace_back(fid);","class":"lineNoCov","hits":"0",},
{"lineNum":"  199","line":"                return stdx::err{allocated.error()};","class":"lineNoCov","hits":"0",},
{"lineNum":"  200","line":"            }"},
{"lineNum":"  201","line":"            pid = *allocated;","class":"lineCov","hits":"1","order":"900",},
{"lineNum":"  202","line":"        }"},
{"lineNum":"  203","line":""},
{"lineNum":"  204","line":"        auto& f{frame_at(fid)};","class":"lineCov","hits":"1","order":"899",},
{"lineNum":"  205","line":"        f.reset(pid);","class":"lineCov","hits":"1","order":"964",},
{"lineNum":"  206","line":""},
{"lineNum":"  207","line":"        f.set_dirty(true);","class":"lineCov","hits":"1","order":"898",},
{"lineNum":"  208","line":"        f.pin();","class":"lineCov","hits":"1","order":"916",},
{"lineNum":"  209","line":"        page_table_.emplace(pid, fid);","class":"lineCov","hits":"1","order":"897",},
{"lineNum":"  210","line":"        replacer_.access(fid);","class":"lineCov","hits":"1","order":"969",},
{"lineNum":"  211","line":"        replacer_.set_evictable(fid, false);","class":"lineCov","hits":"1","order":"966",},
{"lineNum":"  212","line":"        return &f;","class":"lineCov","hits":"1","order":"896",},
{"lineNum":"  213","line":"    }","class":"lineCov","hits":"1","order":"905",},
{"lineNum":"  214","line":""},
{"lineNum":"  215","line":"    [[nodiscard]] auto unpin_page(page_id_t pid, bool dirty) -> result<void> {","class":"lineCov","hits":"1","order":"867",},
{"lineNum":"  216","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"866",},
{"lineNum":"  217","line":"        auto             slot{page_table_.get_opt(pid)};","class":"lineCov","hits":"1","order":"865",},
{"lineNum":"  218","line":"        if (!slot) { return stdx::err{error_t::PAGE_NOT_FOUND}; }","class":"lineCov","hits":"1","order":"864",},
{"lineNum":"  219","line":""},
{"lineNum":"  220","line":"        const auto fid{*slot};","class":"lineCov","hits":"1","order":"862",},
{"lineNum":"  221","line":"        auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"861",},
{"lineNum":"  222","line":"        if (f.pin_count() <= 0) { return stdx::err{error_t::PAGE_NOT_FOUND}; }","class":"lineCov","hits":"1","order":"860",},
{"lineNum":"  223","line":"        if (dirty) { f.set_dirty(true); }","class":"lineCov","hits":"1","order":"859",},
{"lineNum":"  224","line":"        if (f.unpin() == 0) { replacer_.set_evictable(fid, true); }","class":"lineCov","hits":"1","order":"858",},
{"lineNum":"  225","line":"        return {};","class":"lineCov","hits":"1","order":"857",},
{"lineNum":"  226","line":"    }","class":"lineCov","hits":"1","order":"863",},
{"lineNum":"  227","line":""},
{"lineNum":"  228","line":"    // Flush a specific frame in the pool"},
{"lineNum":"  229","line":"    [[nodiscard]] auto flush(page_id_t pid) -> result<void> {"},
{"lineNum":"  230","line":"        std::scoped_lock lock{mutex_};"},
{"lineNum":"  231","line":"        auto             slot{page_table_.get_opt(pid)};"},
{"lineNum":"  232","line":"        if (!slot) { return stdx::err{error_t::PAGE_NOT_FOUND}; }"},
{"lineNum":"  233","line":"        return flush_locked(*slot);"},
{"lineNum":"  234","line":"    }"},
{"lineNum":"  235","line":""},
{"lineNum":"  236","line":"    // Flushes all frames in the buffer"},
{"lineNum":"  237","line":"    [[nodiscard]] auto flush() -> result<void> {","class":"lineCov","hits":"1","order":"958",},
{"lineNum":"  238","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"955",},
{"lineNum":"  239","line":"        for (usize i{0}; i < PoolSize; ++i) { TRY(flush_locked(static_cast<frame_id_t>(i))); }","class":"lineCov","hits":"1","order":"947",},
{"lineNum":"  240","line":"        return {};","class":"lineCov","hits":"1","order":"939",},
{"lineNum":"  241","line":"    }","class":"lineCov","hits":"1","order":"950",},
{"lineNum":"  242","line":""},
{"lineNum":"  243","line":"    // Evicts the provides pid unless it isn\'t resident in which case this is a noop"},
{"lineNum":"  244","line":"    [[nodiscard]] auto delete_page(page_id_t pid) -> result<void> {","class":"lineCov","hits":"1","order":"818",},
{"lineNum":"  245","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"816",},
{"lineNum":"  246","line":"        auto             slot{page_table_.get_opt(pid)};","class":"lineCov","hits":"1","order":"814",},
{"lineNum":"  247","line":"        if (!slot) { return {}; }","class":"lineCov","hits":"1","order":"812",},
{"lineNum":"  248","line":""},
{"lineNum":"  249","line":"        const auto fid{*slot};","class":"lineCov","hits":"1","order":"810",},
{"lineNum":"  250","line":"        auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"803",},
{"lineNum":"  251","line":"        if (f.pin_count() > 0) { return stdx::err{error_t::TREE_CORRUPT}; }","class":"lineCov","hits":"1","order":"802",},
{"lineNum":"  252","line":""},
{"lineNum":"  253","line":"        page_table_.remove(pid);","class":"lineCov","hits":"1","order":"800",},
{"lineNum":"  254","line":"        note_table_removal();","class":"lineCov","hits":"1","order":"799",},
{"lineNum":"  255","line":"        replacer_.remove(fid);","class":"lineCov","hits":"1","order":"798",},
{"lineNum":"  256","line":"        f.reset(INVALID_PAGE_ID);","class":"lineCov","hits":"1","order":"930",},
{"lineNum":"  257","line":"        free_list_.emplace_back(fid);","class":"lineCov","hits":"1","order":"925",},
{"lineNum":"  258","line":"        free_pages_.emplace_back(pid);","class":"lineCov","hits":"1","order":"797",},
{"lineNum":"  259","line":"        return {};","class":"lineCov","hits":"1","order":"796",},
{"lineNum":"  260","line":"    }","class":"lineCov","hits":"1","order":"801",},
{"lineNum":"  261","line":""},
{"lineNum":"  262","line":"    [[nodiscard]] auto fetch_read(page_id_t pid) -> result<read_guard_t> {","class":"lineCov","hits":"1","order":"856",},
{"lineNum":"  263","line":"        auto pg{TRY(fetch_page(pid))};","class":"lineCov","hits":"1","order":"854",},
{"lineNum":"  264","line":"        pg->latch().lock_shared();","class":"lineCov","hits":"1","order":"852",},
{"lineNum":"  265","line":"        return read_guard_t{*this, *pg};","class":"lineCov","hits":"1","order":"850",},
{"lineNum":"  266","line":"    }","class":"lineCov","hits":"1","order":"848",},
{"lineNum":"  267","line":""},
{"lineNum":"  268","line":"    [[nodiscard]] auto fetch_write(page_id_t pid) -> result<write_guard_t> {","class":"lineCov","hits":"1","order":"809",},
{"lineNum":"  269","line":"        auto pg{TRY(fetch_page(pid))};","class":"lineCov","hits":"1","order":"822",},
{"lineNum":"  270","line":"        pg->latch().lock();","class":"lineCov","hits":"1","order":"808",},
{"lineNum":"  271","line":"        return write_guard_t{*this, *pg};","class":"lineCov","hits":"1","order":"807",},
{"lineNum":"  272","line":"    }","class":"lineCov","hits":"1","order":"806",},
{"lineNum":"  273","line":""},
{"lineNum":"  274","line":"    [[nodiscard]] auto new_write() -> result<std::pair<page_id_t, write_guard_t>> {","class":"lineCov","hits":"1","order":"912",},
{"lineNum":"  275","line":"        auto pg{TRY(new_page())};","class":"lineCov","hits":"1","order":"911",},
{"lineNum":"  276","line":"        pg->latch().lock();","class":"lineCov","hits":"1","order":"910",},
{"lineNum":"  277","line":"        return std::make_pair(pg->page_id(), write_guard_t{*this, *pg});","class":"lineCov","hits":"1","order":"909",},
{"lineNum":"  278","line":"    }","class":"lineCov","hits":"1","order":"908",},
{"lineNum":"  279","line":""},
{"lineNum":"  280","line":"    [[nodiscard]] auto pin_count(page_id_t pid) -> stdx::option<i32> {","class":"lineCov","hits":"1","order":"795",},
{"lineNum":"  281","line":"        std::scoped_lock lock{mutex_};","class":"lineCov","hits":"1","order":"804",},
{"lineNum":"  282","line":"        auto             slot{page_table_.get_opt(pid)};","class":"lineCov","hits":"1","order":"893",},
{"lineNum":"  283","line":"        if (!slot) { return stdx::none; }","class":"lineCov","hits":"1","order":"891",},
{"lineNum":"  284","line":"        return frame_at(*slot).pin_count();","class":"lineCov","hits":"1","order":"794",},
{"lineNum":"  285","line":"    }","class":"lineCov","hits":"1","order":"793",},
{"lineNum":"  286","line":""},
{"lineNum":"  287","line":"    [[nodiscard]] auto is_resident(page_id_t pid) -> bool {"},
{"lineNum":"  288","line":"        std::scoped_lock lock{mutex_};"},
{"lineNum":"  289","line":"        return page_table_.contains(pid);"},
{"lineNum":"  290","line":"    }"},
{"lineNum":"  291","line":""},
{"lineNum":"  292","line":"    [[nodiscard]] auto evictable_count() -> usize {"},
{"lineNum":"  293","line":"        std::scoped_lock lock{mutex_};"},
{"lineNum":"  294","line":"        return replacer_.size();"},
{"lineNum":"  295","line":"    }"},
{"lineNum":"  296","line":""},
{"lineNum":"  297","line":"  private:"},
{"lineNum":"  298","line":"    static constexpr usize TABLE_CAPACITY{PoolSize * 2};"},
{"lineNum":"  299","line":"    static constexpr usize REHASH_CHURN_LIMIT{PoolSize / 2 == 0 ? 1UZ : PoolSize / 2};"},
{"lineNum":"  300","line":""},
{"lineNum":"  301","line":"  private:"},
{"lineNum":"  302","line":"    [[nodiscard]] auto frame_at(frame_id_t fid) noexcept -> page& {","class":"lineCov","hits":"1","order":"965",},
{"lineNum":"  303","line":"        return frames_[static_cast<usize>(std::to_underlying(fid))];","class":"lineCov","hits":"1","order":"913",},
{"lineNum":"  304","line":"    }"},
{"lineNum":"  305","line":""},
{"lineNum":"  306","line":"    // Caller needs to hold the mutex"},
{"lineNum":"  307","line":"    [[nodiscard]] auto grab_victim_frame() -> result<frame_id_t> {","class":"lineCov","hits":"1","order":"968",},
{"lineNum":"  308","line":"        if (!free_list_.empty()) {","class":"lineCov","hits":"1","order":"917",},
{"lineNum":"  309","line":"            const auto fid{free_list_.back()};","class":"lineCov","hits":"1","order":"895",},
{"lineNum":"  310","line":"            free_list_.pop_back();","class":"lineCov","hits":"1","order":"904",},
{"lineNum":"  311","line":"            return fid;","class":"lineCov","hits":"1","order":"890",},
{"lineNum":"  312","line":"        }"},
{"lineNum":"  313","line":""},
{"lineNum":"  314","line":"        auto victim{replacer_.evict()};","class":"lineCov","hits":"1","order":"888",},
{"lineNum":"  315","line":"        if (!victim) { return stdx::err{error_t::POOL_EXHAUSTED}; }","class":"lineCov","hits":"1","order":"872",},
{"lineNum":"  316","line":""},
{"lineNum":"  317","line":"        const auto fid{*victim};","class":"lineCov","hits":"1","order":"886",},
{"lineNum":"  318","line":"        auto&      f{frame_at(fid)};","class":"lineCov","hits":"1","order":"884",},
{"lineNum":"  319","line":"        if (f.is_dirty()) {","class":"lineCov","hits":"1","order":"869",},
{"lineNum":"  320","line":"            // If the frame cannot persist then it must stay resident"},
{"lineNum":"  321","line":"            if (auto r{disk_->write_page(f.page_id(), f.data())}; !r) {","class":"lineCov","hits":"1","order":"881",},
{"lineNum":"  322","line":"                replacer_.access(fid);","class":"lineNoCov","hits":"0",},
{"lineNum":"  323","line":"                replacer_.set_evictable(fid, true);","class":"lineNoCov","hits":"0",},
{"lineNum":"  324","line":"                return stdx::err{r.error()};","class":"lineNoCov","hits":"0",},
{"lineNum":"  325","line":"            }"},
{"lineNum":"  326","line":"            f.set_dirty(false);","class":"lineCov","hits":"1","order":"880",},
{"lineNum":"  327","line":"        }"},
{"lineNum":"  328","line":"        page_table_.remove(f.page_id());","class":"lineCov","hits":"1","order":"879",},
{"lineNum":"  329","line":"        note_table_removal();","class":"lineCov","hits":"1","order":"877",},
{"lineNum":"  330","line":"        return fid;","class":"lineCov","hits":"1","order":"876",},
{"lineNum":"  331","line":"    }","class":"lineCov","hits":"1","order":"875",},
{"lineNum":"  332","line":""},
{"lineNum":"  333","line":"    // Caller needs to hold the mutex as this manages manual rehashing"},
{"lineNum":"  334","line":"    auto note_table_removal() -> void {","class":"lineCov","hits":"1","order":"956",},
{"lineNum":"  335","line":"        if (++page_table_churn_ >= REHASH_CHURN_LIMIT) {","class":"lineCov","hits":"1","order":"953",},
{"lineNum":"  336","line":"            page_table_.rehash();","class":"lineCov","hits":"1","order":"945",},
{"lineNum":"  337","line":"            page_table_churn_ = 0;","class":"lineCov","hits":"1","order":"937",},
{"lineNum":"  338","line":"        }"},
{"lineNum":"  339","line":"    }","class":"lineCov","hits":"1","order":"944",},
{"lineNum":"  340","line":""},
{"lineNum":"  341","line":"    [[nodiscard]] auto flush_locked(frame_id_t fid) -> result<void> {","class":"lineCov","hits":"1","order":"933",},
{"lineNum":"  342","line":"        auto& f{frame_at(fid)};","class":"lineCov","hits":"1","order":"929",},
{"lineNum":"  343","line":"        if (!f.is_dirty()) { return {}; }","class":"lineCov","hits":"1","order":"935",},
{"lineNum":"  344","line":"        TRY(disk_->write_page(f.page_id(), f.data()));","class":"lineCov","hits":"1","order":"924",},
{"lineNum":"  345","line":"        f.set_dirty(false);","class":"lineCov","hits":"1","order":"922",},
{"lineNum":"  346","line":"        return {};","class":"lineCov","hits":"1","order":"920",},
{"lineNum":"  347","line":"    }","class":"lineCov","hits":"1","order":"915",},
{"lineNum":"  348","line":""},
{"lineNum":"  349","line":"  private:"},
{"lineNum":"  350","line":"    std::mutex                                                   mutex_;"},
{"lineNum":"  351","line":"    stdx::box<disk_manager>                                      disk_;"},
{"lineNum":"  352","line":"    stdx::box<page[]>                                            frames_;"},
{"lineNum":"  353","line":"    frame_replacer<PoolSize>                                     replacer_;"},
{"lineNum":"  354","line":"    stdx::fixed::vector<frame_id_t, PoolSize>                    free_list_;"},
{"lineNum":"  355","line":"    std::vector<page_id_t>                                       free_pages_;"},
{"lineNum":"  356","line":"    usize                                                        page_table_churn_{0};","class":"lineCov","hits":"1","order":"963",},
{"lineNum":"  357","line":"    stdx::fixed::hash_map<page_id_t, frame_id_t, TABLE_CAPACITY> page_table_;"},
{"lineNum":"  358","line":"};"},
{"lineNum":"  359","line":""},
{"lineNum":"  360","line":"} // namespace cairn::storage"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-07-02 02:41:58", "instrumented" : 184, "covered" : 177,};
var merged_data = [];
