var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include <stdx/hash.hh>"},
{"lineNum":"    4","line":"#include <stdx/option.hh>"},
{"lineNum":"    5","line":"#include <stdx/types.hh>"},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"namespace cairn::txn {"},
{"lineNum":"    8","line":""},
{"lineNum":"    9","line":"enum class id_t : i64 {};"},
{"lineNum":"   10","line":"constexpr id_t INVALID_TXN_ID{-1};"},
{"lineNum":"   11","line":"using id_hash_t = stdx::hash<txn::id_t>;"},
{"lineNum":"   12","line":""},
{"lineNum":"   13","line":"enum class timestamp_t : u64 {};"},
{"lineNum":"   14","line":"constexpr timestamp_t INVALID_TIMESTAMP{stdx::nullable<timestamp_t>::invalid()};"},
{"lineNum":"   15","line":""},
{"lineNum":"   16","line":"enum class isolation_level_t : u8 {"},
{"lineNum":"   17","line":"    SNAPSHOT,"},
{"lineNum":"   18","line":"    SERIALIZABLE,"},
{"lineNum":"   19","line":"    READ_COMMITTED,"},
{"lineNum":"   20","line":"    REPEATABLE_READ,"},
{"lineNum":"   21","line":"};"},
{"lineNum":"   22","line":""},
{"lineNum":"   23","line":"} // namespace cairn::txn"},
{"lineNum":"   24","line":""},
{"lineNum":"   25","line":"namespace stdx {"},
{"lineNum":"   26","line":""},
{"lineNum":"   27","line":"template <> struct nullable<cairn::txn::id_t> {"},
{"lineNum":"   28","line":"    using tid_t = cairn::txn::id_t;"},
{"lineNum":"   29","line":"    [[nodiscard]] static constexpr auto invalid() noexcept -> tid_t {","class":"lineCov","hits":"1","order":"1952",},
{"lineNum":"   30","line":"        return cairn::txn::INVALID_TXN_ID;","class":"lineCov","hits":"1","order":"1951",},
{"lineNum":"   31","line":"    }"},
{"lineNum":"   32","line":""},
{"lineNum":"   33","line":"    [[nodiscard]] static constexpr auto is_valid(const tid_t& id) noexcept -> bool {","class":"lineCov","hits":"1","order":"1954",},
{"lineNum":"   34","line":"        return id != invalid();","class":"lineCov","hits":"1","order":"1953",},
{"lineNum":"   35","line":"    }"},
{"lineNum":"   36","line":"};"},
{"lineNum":"   37","line":""},
{"lineNum":"   38","line":"} // namespace stdx"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-07-24 01:31:31", "instrumented" : 4, "covered" : 4,};
var merged_data = [];
