var data = {lines:[
{"lineNum":"    1","line":"#pragma once"},
{"lineNum":"    2","line":""},
{"lineNum":"    3","line":"#include <string_view>"},
{"lineNum":"    4","line":"#include <utility>"},
{"lineNum":"    5","line":"#include <vector>"},
{"lineNum":"    6","line":""},
{"lineNum":"    7","line":"#include <gsl/span>"},
{"lineNum":"    8","line":"#include <stdx/fixed/string.hh>"},
{"lineNum":"    9","line":"#include <stdx/option.hh>"},
{"lineNum":"   10","line":"#include <stdx/types.hh>"},
{"lineNum":"   11","line":""},
{"lineNum":"   12","line":"#include \"sql/type.hh\""},
{"lineNum":"   13","line":""},
{"lineNum":"   14","line":"namespace cairn::sql {"},
{"lineNum":"   15","line":""},
{"lineNum":"   16","line":"class column {","class":"lineCov","hits":"1","order":"3822",},
{"lineNum":"   17","line":"  public:"},
{"lineNum":"   18","line":"    column(stdx::fixed::string name, type::id_t type, bool nullable = true)"},
{"lineNum":"   19","line":"        : name_{std::move(name)}, type_{type}, nullable_{nullable} {}","class":"lineCov","hits":"1","order":"3827",},
{"lineNum":"   20","line":""},
{"lineNum":"   21","line":"    [[nodiscard]] auto name() const noexcept -> std::string_view { return name_; }","class":"lineCov","hits":"1","order":"3818",},
{"lineNum":"   22","line":"    [[nodiscard]] auto type() const noexcept -> type::id_t { return type_; }","class":"lineCov","hits":"1","order":"3828",},
{"lineNum":"   23","line":"    [[nodiscard]] auto nullable() const noexcept -> bool { return nullable_; }","class":"lineCov","hits":"1","order":"3836",},
{"lineNum":"   24","line":"    [[nodiscard]] auto size() const noexcept -> stdx::option<u32> {","class":"lineCov","hits":"1","order":"3830",},
{"lineNum":"   25","line":"        return type::get_size_of(type_);","class":"lineCov","hits":"1","order":"3833",},
{"lineNum":"   26","line":"    }"},
{"lineNum":"   27","line":""},
{"lineNum":"   28","line":"  private:"},
{"lineNum":"   29","line":"    stdx::fixed::string name_;"},
{"lineNum":"   30","line":"    type::id_t          type_;"},
{"lineNum":"   31","line":"    bool                nullable_;"},
{"lineNum":"   32","line":"};"},
{"lineNum":"   33","line":""},
{"lineNum":"   34","line":"class schema {","class":"lineCov","hits":"1","order":"3834",},
{"lineNum":"   35","line":"  public:"},
{"lineNum":"   36","line":"    explicit schema(std::vector<column> columns) : columns_{std::move(columns)} {","class":"lineCov","hits":"1","order":"3829",},
{"lineNum":"   37","line":"        for (const auto& column : columns_) {","class":"lineCov","hits":"1","order":"3825",},
{"lineNum":"   38","line":"            if (const auto fixed_size{column.size()}) {","class":"lineCov","hits":"1","order":"3824",},
{"lineNum":"   39","line":"                fixed_length_size_ += *fixed_size;","class":"lineCov","hits":"1","order":"3823",},
{"lineNum":"   40","line":"            } else {","class":"lineCov","hits":"1","order":"3821",},
{"lineNum":"   41","line":"                has_varlen_ = true;","class":"lineCov","hits":"1","order":"3820",},
{"lineNum":"   42","line":"            }"},
{"lineNum":"   43","line":"        }"},
{"lineNum":"   44","line":"    }","class":"lineCov","hits":"1","order":"3819",},
{"lineNum":"   45","line":""},
{"lineNum":"   46","line":"    [[nodiscard]] auto columns() const noexcept -> gsl::span<const column> { return columns_; }","class":"lineCov","hits":"1","order":"3837",},
{"lineNum":"   47","line":"    [[nodiscard]] auto operator[](usize index) const -> const column& { return columns_[index]; }","class":"lineCov","hits":"1","order":"3831",},
{"lineNum":"   48","line":"    [[nodiscard]] auto column_count() const noexcept -> usize { return columns_.size(); }","class":"lineCov","hits":"1","order":"3832",},
{"lineNum":"   49","line":""},
{"lineNum":"   50","line":"    // Total size of all fixed length fields combined"},
{"lineNum":"   51","line":"    [[nodiscard]] auto fixed_length_size() const noexcept -> u32 { return fixed_length_size_; }","class":"lineCov","hits":"1","order":"3838",},
{"lineNum":"   52","line":"    [[nodiscard]] auto has_varlen() const noexcept -> bool { return has_varlen_; }"},
{"lineNum":"   53","line":""},
{"lineNum":"   54","line":"  private:"},
{"lineNum":"   55","line":"    std::vector<column> columns_;"},
{"lineNum":"   56","line":"    u32                 fixed_length_size_{0};","class":"lineCov","hits":"1","order":"3826",},
{"lineNum":"   57","line":"    bool                has_varlen_{false};","class":"lineCov","hits":"1","order":"3835",},
{"lineNum":"   58","line":"};"},
{"lineNum":"   59","line":""},
{"lineNum":"   60","line":"} // namespace cairn::sql"},
]};
var percent_low = 25;var percent_high = 75;
var header = { "command" : "", "date" : "2026-07-24 01:31:31", "instrumented" : 21, "covered" : 21,};
var merged_data = [];
